### ISSUE TITLE
JSON building error

### ISSUE THREAD

**Issue by PrabodDunuwila** [wso2/product-micro-integrator#3773] opened 2024-11-13 05:19 UTC
### Description

When trying to log a json payload with `\\\\` getting the below error.
```
[2024-11-11 00:00:12,337] [-1234] [] [PassThroughMessageProcessor-203] ERROR {org.apache.synapse.mediators.builtin.LogMediator} -  Could not build full log message: Error obtaining parser from data source:null
java.lang.RuntimeException: Error obtaining parser from data source:null
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.getDirectReader(OMSourcedElementImpl.java:229)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.forceExpand(OMSourcedElementImpl.java:252)
	at org.apache.axiom.om.impl.llom.OMSourcedElementImpl.internalSerialize(OMSourcedElementImpl.java:677)

Caused by: javax.xml.stream.XMLStreamException
	at org.apache.synapse.commons.staxon.core.base.AbstractXMLStreamReader.initialize(AbstractXMLStreamReader.java:245)
	at org.apache.synapse.commons.staxon.core.json.JsonXMLStreamReader.<init>(JsonXMLStreamReader.java:88)
	at org.apache.synapse.commons.staxon.core.json.JsonXMLInputFactory.createXMLStreamReader(JsonXMLInputFactory.java:170)
```
### Steps to Reproduce

-

### Version

EI 6.4.0

**Comment by malakaganga** [comment] 2024-11-21 10:15
Duplicate of: https://github.com/wso2/product-ei/issues/3775

**Closed by malakaganga** 2024-11-21 10:15 UTC
Labels: Type/Bug
